---    
- name: ansible administration
  hosts: all
  tasks:
  - name: create a group
    group:
      name: manage
      state: present
  - name: cretae a security group
    group:
      name: security
      state: present
       
  - name: create a dravid user profile
    user:
      name: dravid
      uid: 41003
      shell: /bin/bash
      groups: manage,security
      append: yes
       
  - name: give privilege to the group
    copy:
      content: " %manage ALL=(ALL) NOPASSWD: ALL"
      dest: /etc/sudoers.d/manage
