name: 'Terraform Run'

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
  workflow_dispatch:



jobs:
  terraform:
    name: 'Terraform Run'
    runs-on: self-hosted


    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install Terraform
      run: |
          sudo yum install -y yum-utils
          sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
          sudo sed -i 's/\$releasever/9/g' /etc/yum.repos.d/hashicorp.repo
          sudo yum clean all
          sudo yum makecache
          sudo yum install terraform -y
          terraform --version
