name: Run Ansible Playbook
on:
 workflow_dispatch:
 

jobs:
  ansible-playbook:
    runs-on: [ ansible-master ]  # Change this if you're not using a self-hosted runner

    steps:
      - uses: actions/checkout@v4

      - name: Execute Ansible Playbook
 
        run: |
           ansible-playbook  playbook3-ansible-administration.yaml -i /home/videl/ansible/inventory.yaml --become
